---
cluster_engine: LSF

use_cluster: true

ref: b37

aligner: bwamem
bam_chr1_base_recal: true
bam_dup_type: markdup
bam_no_filter: false
bam_no_recal: false
bam_no_realn: false
bam_no_sort: false
bam_fix_rg: false
bam_phred64: false
bam_reprocess: false

# Mutation callers and filtering
snv_type: mutect
mutect_split_chr: true
mutect_use_contest: false
indel_types: varscan_indels strelka_indels scalpel_indels lancet_indels platypus_indels
vcf_post_ann_filter_expression: ExAC_AF > 0.01

# Annotations
ann_facets: true
ann_mut_taste: false
ann_provean: false
ann_pathogen: false

# Target panels BED files
# exome: true
# targets_file: ~/share/reference/target_panels/

# FACETS
gatk_hard_filter_snps: true
gatk_pool_snp_recal: false
facets_pre_cval: 50
facets_cval1: 150
facets_cval2: 50
facets_min_nhet: 25
facets_union_gatk_dbsnp: false

# CNVKIT
ontarget_file: ~/share/reference/target_panels/MSK-IMPACT-468_CNVkit_ontarget.bed
offtarget_file: ~/share/reference/target_panels/MSK-IMPACT-468_CNVkit_offtarget.bed

# MSK-ACCESS
marianas_umi_length: 3
marianas_min_mapq: 1
marianas_min_baq: 20
marianas_mismatch: 0
marianas_wobble: 1
marianas_min_consensus: 90
waltz_min_mapq: 20
waltz_bed_file: ~/share/reference/target_panels/MSK-ACCESS-v1_0-probe-A.waltz.bed

qsub_priority: 0
...
